version: "3.7"
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_hokt
    volumes:
      - ./database:/var/lib/minesql
    environment:
      MYSQL_USER: sbcntruser
      MYSQL_PASSWORD: sbcntrpass
      MYSQL_DATABASE: sbcntrapp
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
    ports:
      - 3306:3306
  backend:
    image: sbcntr-backend:latest
    depends_on:
      db:
        condition: service_healthy
    container_name: sbcntr-backend
    environment:
      DB_HOST: db
      DB_USERNAME: sbcntruser
      DB_PASSWORD: sbcntrpass
      DB_NAME: sbcntrapp
    ports:
      - 3200:80
  frontend:
    image: sbcntr-frontend:latest
    depends_on:
      db:
        condition: service_healthy
    container_name: sbcntr-frontend
    environment:
      DB_HOST: db
      DB_USERNAME: sbcntruser
      DB_PASSWORD: sbcntrpass
      DB_NAME: sbcntrapp
      SESSION_SECRET_KEY: 41b678c65b37bf99c37bcab522802760
      APP_SERVICE_HOST: "http://backend"
      NOTIF_SERVICE_HOST: "http://backend"
    ports:
      - 3100:80
